GET http://localhost:3002/img/image.png HTTP/1.1
# content-type: application/json
content-type: image/png

# {
#   "name": "Bamboo Watch",
#   "description": "Product Description",
#   "images": ["bamboo-watch.jpg"],
#   "price": 65.00,
#   "category": "Accessories",
#   "quantity": 24,
# }

# {"name":"12","description":"12","price":12,"quantity":12,"category":"Accessories"}