GET http://localhost:3002/api/products HTTP/1.1
content-type: application/json

# {
#   "id": "1000",
#   "name": "Bamboo Watch",
#   "description": "Product Description",
#   "images": ["bamboo-watch.jpg"],
#   "price": 65.00,
#   "category": "Accessories",
#   "quantity": 24,
#   "ratingScore": 5,
#   "ratingCount": 2
# }