# GET http://localhost:3002/api/images?id=101 HTTP/1.1
GET https://primefaces.org/cdn/primevue/images/product/bamboo-watch.jpg HTTP/1.1
# content-type: application/json
# content-type: image/png

# {
#   "name": "Bamboo Watch",
#   "description": "Product Description",
#   "price": 65.00,
#   "category": "Accessories",
#   "quantity": 24,
# }